"""Wireshark dissection mapping table, shared by the tshark JSON, tshark EK and PyShark readers.

Each packet is one record whose fields are Wireshark display-filter fields ("ip.src", "tcp.flags"),
the names of the Wireshark Display Filter Reference. tshark -T json nests them in protocol trees,
tshark -T ek prefixes them with their layer and replaces dots with underscores, PyShark exposes them
per layer; every reader flattens a packet to {display-filter field: value or list of values} and maps
it through this one table. Where Wireshark renamed a protocol (bootp to dhcp, ssl to tls in 3.0) both
spellings are rows. A field the table does not list is retained as an attribute "wireshark.<field>".
"""

from __future__ import annotations

from nagahana.datamodel.native import R, RecordMap
from nagahana.datamodel.spec import Level

REF = "Wireshark Display Filter Reference (Wireshark 3.x and 4.x)"

PACKET = RecordMap(
    "wireshark", "packet", "Wireshark packet dissection (tshark JSON / EK, PyShark)", Level.PACKET, (
        R("frame.time_epoch", "s", "@time", "time", note="Decimal epoch seconds, or RFC 3339 text (tshark 4.x)."),
        R("frame.number", "i", conv="count"),
        R("frame.len", "i", conv="count", unit="bytes"),
        R("frame.cap_len", "i", conv="count", unit="bytes"),
        R("frame.protocols", "s", kind="fp"),
        R("frame.interface_id", "i", conv="count"),
        R("frame.interface_name", "s"),
        R("eth.src", "m", "flow.src_mac", "mac"),
        R("eth.dst", "m", "flow.dst_mac", "mac"),
        R("eth.type", "s", conv="", note="EtherType, hex."),
        R("vlan.id", "i", "flow.vlan", "first_int"),
        R("vlan.priority", "i", conv="count"),
        R("sll.src.eth", "m", "flow.src_mac", "mac"),
        R("sll.pkttype", "i", conv="count"),
        R("ip.version", "i", "flow.ip_version", "count"),
        R("ip.hdr_len", "i", conv="count", unit="bytes"),
        R("ip.dsfield", "s", "flow.ip_tos", "hex"),
        R("ip.tos", "s", "flow.ip_tos", "hex", note="Wireshark before 1.10."),
        R("ip.len", "i", "pkt.ip_len_min", "count", unit="bytes", note="Also pkt.ip_len_max and flow.bytes_fwd."),
        R("ip.id", "s", conv=""),
        R("ip.flags", "s", conv=""),
        R("ip.flags.df", "i", "pkt.ip_df_count", "flag01"),
        R("ip.flags.mf", "i", "pkt.ip_mf_count", "flag01"),
        R("ip.frag_offset", "i", conv="count"),
        R("ip.ttl", "i", "pkt.ttl_mean", "count", unit="hops", note="Also pkt.ttl_min and pkt.ttl_max."),
        R("ip.proto", "i", "flow.protocol", "count"),
        R("ip.checksum", "s"),
        R("ip.src", "a", "flow.src_ip", "addr"),
        R("ip.dst", "a", "flow.dst_ip", "addr"),
        R("ipv6.version", "i", conv="count"),
        R("ipv6.tclass", "s", "flow.ip_tos", "hex"),
        R("ipv6.flow", "s"),
        R("ipv6.plen", "i", conv="count", unit="bytes", note="Payload length; IP length = plen + 40."),
        R("ipv6.nxt", "i", conv="count", note="First next header; the transport protocol comes from the layers."),
        R("ipv6.hlim", "i", "pkt.ttl_mean", "count", unit="hops"),
        R("ipv6.src", "a", "flow.src_ip", "addr"),
        R("ipv6.dst", "a", "flow.dst_ip", "addr"),
        R("tcp.srcport", "i", "flow.src_port", "port"),
        R("tcp.dstport", "i", "flow.dst_port", "port"),
        R("tcp.stream", "i", conv="count"),
        R("tcp.len", "i", "flow.payload_bytes_fwd", "count", unit="bytes"),
        R("tcp.seq", "i", conv="count", note="Relative sequence number."),
        R("tcp.seq_raw", "i", conv="count"),
        R("tcp.ack", "i", conv="count"),
        R("tcp.ack_raw", "i", conv="count"),
        R("tcp.hdr_len", "i", conv="count", unit="bytes"),
        R("tcp.flags", "s", "flow.tcp_flags_fwd", "hex_tcp_bits8", also="native"),
        R("tcp.window_size_value", "i", conv="count", unit="bytes",
          note="Raw window; it is pkt.tcp_window_init_fwd on a SYN without ACK."),
        R("tcp.window_size", "i", conv="count", unit="bytes"),
        R("tcp.window_size_scalefactor", "i", conv="int"),
        R("tcp.analysis.retransmission", "s", "pkt.retransmissions", "present_one"),
        R("tcp.analysis.fast_retransmission", "s", conv="present_bool"),
        R("tcp.analysis.duplicate_ack", "s", conv="present_bool"),
        R("tcp.analysis.lost_segment", "s", conv="present_bool"),
        R("tcp.time_delta", "f", conv="double", unit="s"),
        R("tcp.time_relative", "f", conv="double", unit="s"),
        R("udp.srcport", "i", "flow.src_port", "port"),
        R("udp.dstport", "i", "flow.dst_port", "port"),
        R("udp.length", "i", conv="count", unit="bytes"),
        R("udp.stream", "i", conv="count"),
        R("icmp.type", "i", "proto.icmp.type", "count"),
        R("icmp.code", "i", "proto.icmp.code", "count"),
        R("icmpv6.type", "i", "proto.icmp.type", "count"),
        R("icmpv6.code", "i", "proto.icmp.code", "count"),
        R("arp.opcode", "i", "proto.arp.opcode", "count"),
        R("arp.src.hw_mac", "m", "flow.src_mac", "mac"),
        R("arp.src.proto_ipv4", "a", "flow.src_ip", "addr"),
        R("arp.dst.proto_ipv4", "a", "flow.dst_ip", "addr"),
        R("dns.id", "s", "proto.dns.trans_id", "hex"),
        R("dns.flags", "s", "proto.dns.flags", "dns_flags_word", also="native",
          note="The 16-bit header flags word; the bit fields below are used when it is absent."),
        R("dns.flags.response", "i", conv="flag01"),
        R("dns.flags.opcode", "i", "proto.dns.opcode", "count"),
        R("dns.flags.authoritative", "i", "proto.dns.flags", "bit:0x01"),
        R("dns.flags.truncated", "i", "proto.dns.flags", "bit:0x02"),
        R("dns.flags.recdesired", "i", "proto.dns.flags", "bit:0x04"),
        R("dns.flags.recavail", "i", "proto.dns.flags", "bit:0x08"),
        R("dns.flags.z", "i", "proto.dns.flags", "bit:0x10"),
        R("dns.flags.authenticated", "i", "proto.dns.flags", "bit:0x20"),
        R("dns.flags.checkdisable", "i", "proto.dns.flags", "bit:0x40"),
        R("dns.flags.rcode", "i", "proto.dns.rcode", "count"),
        R("dns.qry.name", "s", "proto.dns.query", "string"),
        R("dns.qry.type", "i", "proto.dns.qtype", "count"),
        R("dns.qry.class", "s", "proto.dns.qclass", "hex"),
        R("dns.count.answers", "i", "proto.dns.answer_count", "count"),
        R("dns.resp.ttl", "F", "proto.dns.ttls", "list_float", unit="s"),
        R("dns.a", "A", conv="list_addr"),
        R("dns.aaaa", "A", conv="list_addr"),
        R("dns.cname", "S", conv="list"),
        R("dns.time", "f", "proto.dns.rtt", "double", unit="s"),
        R("http.request.method", "s", "proto.http.method", "code:http_method", also="proto.http.method_text"),
        R("http.request.uri", "s", "proto.http.uri", "string"),
        R("http.request.version", "s", "proto.http.version", "string"),
        R("http.response.version", "s"),
        R("http.host", "s", "proto.http.host", "string"),
        R("http.user_agent", "s", "proto.http.user_agent", "string"),
        R("http.referer", "s", "proto.http.referrer", "string"),
        R("http.response.code", "i", "proto.http.status_code", "count"),
        R("http.response.phrase", "s", "proto.http.status_msg", "string"),
        R("http.content_type", "s", "proto.http.content_type", "string"),
        R("http.content_length", "i", conv="count", unit="bytes",
          note="Body length of the message: request or response by which line the packet carries."),
        R("tls.handshake.type", "I", conv="list_int"),
        R("tls.handshake.version", "s", "proto.tls.version", "hex_first"),
        R("tls.record.version", "s"),
        R("tls.handshake.extensions_server_name", "s", "proto.tls.sni", "string"),
        R("tls.handshake.ciphersuite", "s", "proto.tls.cipher", "string",
          note="Mapped for a ServerHello (handshake type 2) only."),
        R("tls.handshake.ja3", "s", "proto.tls.ja3", "string"),
        R("tls.handshake.ja3s", "s", "proto.tls.ja3s", "string"),
        R("tls.handshake.ja4", "s", "proto.tls.ja4", "string"),
        R("tls.alert_message.desc", "i", "proto.tls.alert", "count"),
        R("ssl.handshake.extensions_server_name", "s", "proto.tls.sni", "string", note="Wireshark before 3.0."),
        R("ssl.handshake.version", "s", "proto.tls.version", "hex_first"),
        R("ssh.protocol", "s", kind="fp", note="SSH banner of the side that sent the packet."),
        R("smb2.cmd", "i", "proto.smb.command", "count"),
        R("smb.cmd", "i", "proto.smb.command", "smb1_cmd"),
        R("smb2.nt_status", "s", "proto.smb.status", "hex"),
        R("smb.nt_status", "s", "proto.smb.status", "hex"),
        R("smb2.filename", "s", "file.name", "string"),
        R("smb2.tree", "s", "proto.smb.path", "string"),
        R("kerberos.msg_type", "i", "proto.kerberos.msg_type", "count"),
        R("kerberos.error_code", "i", "proto.kerberos.error_code", "count"),
        R("kerberos.etype", "I", "proto.kerberos.etype", "first_int", also="native"),
        R("kerberos.CNameString", "s", "proto.kerberos.client", "string"),
        R("kerberos.SNameString", "S", "proto.kerberos.service", "join_slash"),
        R("kerberos.realm", "s", "proto.kerberos.realm", "string"),
        R("ntlmssp.auth.username", "s", "auth.user", "string"),
        R("ntlmssp.auth.domain", "s", "auth.domain", "string"),
        R("ntlmssp.auth.hostname", "s", "auth.workstation", "string"),
        R("dhcp.option.dhcp", "i", "proto.dhcp.message_type", "count"),
        R("bootp.option.dhcp", "i", "proto.dhcp.message_type", "count", note="Wireshark before 3.0."),
        R("dhcp.hw.mac_addr", "m", "proto.dhcp.client_mac", "mac"),
        R("dhcp.ip.your", "a", "proto.dhcp.assigned_addr", "addr_nonzero"),
        R("dhcp.option.requested_ip_address", "a", "proto.dhcp.requested_addr", "addr"),
        R("dhcp.option.hostname", "s", "proto.dhcp.hostname", "string"),
        R("dhcp.option.ip_address_lease_time", "i", "proto.dhcp.lease_time", "interval", unit="s"),
        R("ntp.flags.mode", "i", "proto.ntp.mode", "count"),
        R("ntp.flags.vn", "i", "proto.ntp.version", "count"),
        R("ntp.stratum", "i", "proto.ntp.stratum", "count"),
        R("ftp.request.command", "s", "proto.ftp.command", "string"),
        R("ftp.request.arg", "s", "proto.ftp.argument", "string"),
        R("ftp.response.code", "i", "proto.ftp.reply_code", "count"),
        R("mbtcp.trans_id", "i", "ot.modbus.transaction_id", "count"),
        R("mbtcp.unit_id", "i", "ot.modbus.unit_id", "count"),
        R("modbus.func_code", "i", "ot.modbus.function_code", "modbus_fc"),
        R("modbus.exception_code", "i", "ot.modbus.exception_code", "count"),
        R("modbus.reference_num", "i", "ot.modbus.register_start", "count"),
        R("modbus.word_cnt", "i", "ot.modbus.register_count", "count"),
        R("modbus.bit_cnt", "i", "ot.modbus.register_count", "count"),
        R("dnp3.al.func", "i", "ot.dnp3.function_code", "count"),
        R("dnp3.al.iin", "s", "ot.dnp3.iin", "hex"),
        R("dnp3.al.obj", "I", "ot.dnp3.object_group", "dnp3_group"),
        R("iec60870_asdu.typeid", "i", "ot.iec104.type_id", "count"),
        R("iec60870_asdu.causetx", "i", "ot.iec104.cot", "count"),
        R("mqtt.msgtype", "i", "proto.mqtt.message_type", "count"),
        R("mqtt.topic", "s", "proto.mqtt.topic", "string"),
        R("mqtt.qos", "i", "proto.mqtt.qos", "count"),
        R("mqtt.clientid", "s", "proto.mqtt.client_id", "string"),
    ), REF, ocsf_class=4001,
    notes=(
        "One state update per packet (packet granularity, as the PCAP adapter's packet mode): flow.packets_fwd = 1, "
        "flow.bytes_fwd = pkt.ip_len_min = pkt.ip_len_max = the IP length (ip.len, or ipv6.plen + 40), "
        "pkt.ttl_min = pkt.ttl_max = the TTL; flow.tcp_flags = tcp.flags & 0x3F; flow.protocol from the "
        "transport layer when ipv6.nxt names an extension header.",
        "Repeated fields keep their order; a list-valued row maps the whole list, a scalar row its first element.",
        "http.content_length goes to proto.http.request_body_len when the packet carries a request line, else to "
        "proto.http.response_body_len; proto.dns.answers joins the a, aaaa and cname answers in that order.",
        "Entities: initiator = the packet's sender, responder = its receiver, service for TCP and UDP.",
    ),
)

WIRESHARK_MAPS: tuple[RecordMap, ...] = (PACKET,)
