"""Command line of the LR baseline family: `python -m nagahana lr <command>`.

Commands

    write-config     write conf/baselines/lr/*.yaml from the configuration dataclasses (the single source of
                     truth: every YAML default is the dataclass default)
    extract          labelled sources -> stream segments -> split manifest -> LR corpus directory
    fit              fit the family on a corpus (training and validation records) -> model bundle
    cross-validate   run the hyperparameter selection of one member and write its score table (JSON)
    calibrate        refit the detector's calibration and thresholds on the labelled updates of given roles
    predict          one ModelOutputs record (save_outputs .npz) holding the requested splits (all four by
                     default, as the evaluation reads them), optionally with the reference outputs

Sources file of `extract` (YAML):

    sources:
      - kind: pcap                 # pcap | csv-cic | csv-ctu13 | csv-ciciot2023
        path: capture.pcap
        network: site-a
        dataset: cse-cic-ids2018   # dataset name; for CSV kinds also the label mapping (data/labels.py MAPPERS)
        labeller: cic2018-infiltration-slice   # pcap only (training/runs.py LABELLERS)
        sandboxed: true            # pcap only, required
        utc_offset_hours: -4       # csv only, optional
        internal_networks: [10.0.0.0/8]        # csv only, optional

Nothing is defaulted that the data pipeline requires explicitly: the preset, the seed and, for captures,
the sandbox flag are required arguments.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from nagahana.core.errors import ConfigMissing, InvariantViolation

from .config import TASK_NAMES, LRBaselineConfig, config_to_dict, load_config

#: Generated configuration files: name -> (description, overrides applied to the defaults).
CONFIG_FILES: dict[str, tuple[str, dict[str, Any]]] = {
    "lr.yaml": ("Defaults of the LR baseline family (selection by blocked temporal cross-validation).", {}),
    "lr-validation-selection.yaml": (
        "The LR family with every hyperparameter chosen on the validation split (the literal reading of the "
        "evaluation chapter; AS-511).",
        {"detector": {"selection": {"method": "validation"}}, "hazard": {"selection": {"method": "validation"}},
         "stage": {"selection": {"method": "validation"}}, "ridge": {"selection": {"method": "validation"}}}),
}


def _merge(base: dict[str, Any], over: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for k, v in over.items():
        out[k] = _merge(out[k], v) if isinstance(v, dict) and isinstance(out.get(k), dict) else v
    return out


def config_for(name: str) -> LRBaselineConfig:
    """The configuration of a generated file, built from the dataclass defaults and its overrides."""
    from .config import from_dict

    if name not in CONFIG_FILES:
        raise InvariantViolation(f"unknown configuration file {name!r}; known: {sorted(CONFIG_FILES)}")
    return from_dict(LRBaselineConfig, _merge(config_to_dict(LRBaselineConfig()), CONFIG_FILES[name][1]))


def render_config(name: str) -> str:
    """The exact text of a generated configuration file."""
    import yaml

    desc, _over = CONFIG_FILES[name]
    head = ("# Generated by `python -m nagahana lr write-config` from nagahana/baselines/lr/config.py.\n"
            "# Do not edit by hand: the dataclasses are the single source of truth; change them and regenerate.\n"
            f"# {desc}\n")
    body = yaml.safe_dump({"lr": config_to_dict(config_for(name))}, sort_keys=False, default_flow_style=False, width=110)
    return head + body


def write_configs(directory: str | Path) -> list[Path]:
    out = []
    d = Path(directory)
    d.mkdir(parents=True, exist_ok=True)
    for name in CONFIG_FILES:
        p = d / name
        p.write_text(render_config(name), encoding="utf-8", newline="\n")
        out.append(p)
    return out


def _cmd_write_config(args: argparse.Namespace) -> int:
    for p in write_configs(args.out):
        print(f"wrote {p}")
    return 0


def _load_sources(spec_path: str) -> list[Any]:
    """Read the sources file and build PreparedSources (module docstring)."""
    from nagahana.core.config import load_yaml
    from nagahana.data.labels import MAPPERS, map_labels
    from nagahana.data.windows import SourceData, prepare_source

    spec = load_yaml(spec_path)
    entries = spec.get("sources")
    if not isinstance(entries, list) or not entries:
        raise ConfigMissing(f"{spec_path}: a non-empty 'sources' list is required")
    out = []
    for i, e in enumerate(entries):
        for key in ("kind", "path", "network", "dataset"):
            if key not in e:
                raise ConfigMissing(f"{spec_path}: source {i} needs '{key}'")
        kind = str(e["kind"])
        if kind == "pcap":
            from nagahana.ingest.pcap import PcapSource
            from nagahana.training.runs import LABELLERS

            if "sandboxed" not in e or "labeller" not in e:
                raise ConfigMissing(f"{spec_path}: pcap source {i} needs 'sandboxed' and 'labeller'")
            if e["labeller"] not in LABELLERS:
                raise ConfigMissing(f"unknown labeller {e['labeller']!r}; known: {sorted(LABELLERS)}")
            cu = PcapSource(e["path"], sandboxed=bool(e["sandboxed"]), emit="flow-state").columnar()
            labels = LABELLERS[e["labeller"]](cu)
        elif kind in ("csv-cic", "csv-ctu13", "csv-ciciot2023"):
            from nagahana.ingest.csv_flows import CICFlowSource, CICIoT2023Source, CTU13Source

            adapter = {"csv-cic": CICFlowSource, "csv-ctu13": CTU13Source, "csv-ciciot2023": CICIoT2023Source}[kind]
            kw: dict[str, Any] = {}
            for key in ("utc_offset_hours", "internal_networks", "max_rows"):
                if key in e:
                    kw[key] = e[key]
            read = adapter(e["path"], **kw).read()
            mapping = str(e.get("labels", e["dataset"]))
            if mapping not in MAPPERS:
                raise ConfigMissing(f"no label mapping {mapping!r}; known: {sorted(MAPPERS)} (set 'labels')")
            cu, labels = read.updates, map_labels(read.labels, mapping)
        else:
            raise ConfigMissing(f"unknown source kind {kind!r}")
        out.append(prepare_source(SourceData(cu, labels, network=str(e["network"]), dataset=str(e["dataset"]))))
    return out


def _cmd_extract(args: argparse.Namespace) -> int:
    from nagahana.data.sampling import SplitPolicy, assign_splits
    from nagahana.data.stream import default_segment_seconds, plan_stream, segment_records
    from nagahana.models.config import preset

    from .corpus import build_corpus

    cfg = preset(args.preset)
    sources = _load_sources(args.sources)
    seconds = args.segment_seconds if args.segment_seconds is not None else default_segment_seconds(cfg)
    records = []
    for i, src in enumerate(sources):
        records += segment_records(i, src, plan_stream(src, cfg), segment_seconds=seconds)
    policy = SplitPolicy.from_config(cfg, novel_families=frozenset(args.novel_families or ()),
                                     held_out_networks=frozenset(args.held_out_networks or ()), purge=args.purge)
    manifest = assign_splits(records, policy)
    manifest.validate()
    corpus = build_corpus(sources, manifest, cfg, progress=print)
    corpus.save(args.out)
    print(f"wrote {args.out}: {len(corpus.sources)} sources, {sum(s.n_updates for s in corpus.sources)} updates, "
          f"{sum(s.n_triggers for s in corpus.sources)} triggers")
    return 0


def _cmd_fit(args: argparse.Namespace) -> int:
    from .corpus import LRCorpus
    from .family import LRFamily

    corpus = LRCorpus.load(args.corpus)
    cfg = load_config(args.config)
    fam = LRFamily.fit(corpus, cfg, tasks=tuple(args.tasks), progress=print)
    digest = fam.save(args.out)
    print(json.dumps(fam.summary(), indent=1, default=str))
    print(f"saved {args.out} (sha256 {digest[:16]})")
    return 0


def _cmd_cross_validate(args: argparse.Namespace) -> int:
    from .corpus import LRCorpus
    from .family import LRFamily

    corpus = LRCorpus.load(args.corpus)
    cfg = load_config(args.config)
    fam = LRFamily.fit(corpus, cfg, tasks=(args.task,), progress=print)
    member = {"detection": fam.detector, "forecast": fam.hazard, "stage": fam.stage, "state_forecast": fam.ridge}[args.task]
    sel = getattr(member, "selection", None)
    report = {"task": args.task, "selection": sel.as_dict() if sel is not None else None, "fitted": fam.summary()}
    Path(args.out).write_text(json.dumps(report, indent=1, default=str), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


def _cmd_calibrate(args: argparse.Namespace) -> int:
    from .corpus import LRCorpus
    from .design import Contexts
    from .family import LRFamily

    fam = LRFamily.load(args.model)
    if fam.detector is None:
        raise InvariantViolation("the model has no detector to calibrate")
    corpus = LRCorpus.load(args.corpus)
    fam.detector = fam.detector.recalibrate(corpus, Contexts(corpus, fam.encoder), tuple(args.roles), method=args.method,
                                            rule=args.rule, alpha=args.alpha)
    digest = fam.save(args.out)
    print(json.dumps(fam.summary().get("detection", {}), indent=1, default=str))
    print(f"saved {args.out} (sha256 {digest[:16]})")
    return 0


def _cmd_predict(args: argparse.Namespace) -> int:
    from nagahana.evaluation.predictions import save_outputs

    from .corpus import LRCorpus
    from .family import LRFamily

    fam = LRFamily.load(args.model)
    corpus = LRCorpus.load(args.corpus)
    out = fam.predict(corpus, tuple(args.splits), protocol=args.protocol)
    save_outputs(out, args.out)
    print(f"wrote {args.out}: {', '.join(out.tasks())} for splits {', '.join(args.splits)}")
    if args.references:
        d = Path(args.references)
        d.mkdir(parents=True, exist_ok=True)
        for name, ref in fam.references(corpus, tuple(args.splits), protocol=args.protocol).items():
            if ref.tasks():
                save_outputs(ref, d / f"{name}.npz")
                print(f"wrote {d / f'{name}.npz'}")
    return 0


def _csv_list(text: str) -> list[str]:
    return [t for t in (s.strip() for s in text.split(",")) if t]


def register_cli(subparsers: Any) -> argparse.ArgumentParser:
    """Add the `lr` command and its subcommands to an argparse subparsers object (no heavy imports here)."""
    tasks = TASK_NAMES
    lr = subparsers.add_parser("lr", help="logistic-regression baseline family (fit, predict, cross-validate, calibrate)")
    sub = lr.add_subparsers(dest="lr_command", required=True)
    w = sub.add_parser("write-config", help="write conf/baselines/lr/*.yaml from the config dataclasses")
    w.add_argument("--out", required=True, help="directory (conf/baselines/lr)")
    w.set_defaults(func=_cmd_write_config)
    e = sub.add_parser("extract", help="labelled sources -> LR corpus directory")
    e.add_argument("--sources", required=True, help="YAML sources file (see the module docstring)")
    e.add_argument("--preset", required=True, choices=("L", "tiny"), help="NagaHana configuration that defines the windows")
    e.add_argument("--out", required=True, help="corpus directory")
    e.add_argument("--novel-families", type=_csv_list, default=None, help="comma-separated families held out as novel")
    e.add_argument("--held-out-networks", type=_csv_list, default=None, help="comma-separated networks held out (zero-shot)")
    e.add_argument("--purge", type=int, required=True, help="records purged at each chronological cut (AS-327)")
    e.add_argument("--segment-seconds", type=float, default=None, help="segment length (default K * cadence, AS-333)")
    e.set_defaults(func=_cmd_extract)
    f = sub.add_parser("fit", help="fit the family on a corpus")
    f.add_argument("--corpus", required=True)
    f.add_argument("--config", required=True, help="conf/baselines/lr/<name>.yaml")
    f.add_argument("--out", required=True, help="model bundle (.npz)")
    f.add_argument("--tasks", type=_csv_list, default=list(tasks), help=f"comma-separated subset of {','.join(tasks)}")
    f.set_defaults(func=_cmd_fit)
    c = sub.add_parser("cross-validate", help="hyperparameter selection table of one member")
    c.add_argument("--corpus", required=True)
    c.add_argument("--config", required=True)
    c.add_argument("--task", required=True, choices=tasks)
    c.add_argument("--out", required=True, help="JSON report")
    c.set_defaults(func=_cmd_cross_validate)
    k = sub.add_parser("calibrate", help="refit the detector's calibration and thresholds")
    k.add_argument("--model", required=True)
    k.add_argument("--corpus", required=True)
    k.add_argument("--roles", type=_csv_list, required=True, help="roles whose labelled updates calibrate (e.g. val)")
    k.add_argument("--out", required=True)
    k.add_argument("--method", choices=("platt", "isotonic", "temperature", "none"), default=None)
    k.add_argument("--rule", choices=("max_f1", "fixed_fpr", "youden"), default=None)
    k.add_argument("--alpha", type=float, default=None)
    k.set_defaults(func=_cmd_calibrate)
    p = sub.add_parser("predict", help="one ModelOutputs record holding the requested splits")
    p.add_argument("--model", required=True)
    p.add_argument("--corpus", required=True)
    p.add_argument("--splits", type=_csv_list, default=["train", "val", "test", "zero_shot"],
                   help="comma-separated splits held in the one record (default: all four)")
    p.add_argument("--protocol", required=True, help="protocol id (P1 ... P8)")
    p.add_argument("--out", required=True, help="outputs .npz (evaluation/predictions.save_outputs)")
    p.add_argument("--references", default=None, help="directory for persistence and climatology outputs")
    p.set_defaults(func=_cmd_predict)
    return lr


def main(argv: Sequence[str] | None = None) -> int:
    """Run the `lr` commands on their own (the same parser `register_cli` adds to the main CLI)."""
    parser = argparse.ArgumentParser(prog="nagahana-lr")
    sub = parser.add_subparsers(dest="command", required=True)
    register_cli(sub)
    args = parser.parse_args(list(argv) if argv is not None else None)
    return int(args.func(args))


__all__ = ["CONFIG_FILES", "config_for", "main", "register_cli", "render_config", "write_configs"]
