"""Decision report: what is decided, held or proposed, and which code depends on each.

`python -m nagahana decisions` prints it. `--write-docs` writes docs/decisions.md. The code-usage
column is found by scanning the source tree for decision IDs and slugs in `require(...)`,
`require_proposal(...)` and `requires=(...)`. The report therefore stays true as code changes, with
no hand-maintained list.
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

from nagahana.governance import decisions

_SRC = Path(__file__).resolve().parents[1]


def usages() -> dict[str, list[str]]:
    """decision id → sorted list of source files that reference it (by ID or slug)."""
    keys = {d.id: d.id for d in decisions.all_entries()}
    keys.update({d.slug: d.id for d in decisions.all_entries()})
    pattern = re.compile(r"""["']([DP]-\d+[abc]?|[a-z0-9]+(?:-[a-z0-9]+)+)["']""")
    found: dict[str, set[str]] = defaultdict(set)
    for path in _SRC.rglob("*.py"):
        if path.name == "decisions.py":
            continue
        rel = path.relative_to(_SRC.parent).as_posix()
        for m in pattern.finditer(path.read_text(encoding="utf-8")):
            if m.group(1) in keys:
                found[keys[m.group(1)]].add(rel)
    return {k: sorted(v) for k, v in found.items()}


def markdown() -> str:
    """The full report as Markdown."""
    use = usages()
    lines = [
        "# Decisions, as enforced in code",
        "",
        "Generated by `python -m nagahana decisions --write-docs` from "
        "`src/nagahana/governance/decisions.py`. Do not edit by hand.",
        "",
    ]
    for status in (decisions.Status.HELD, decisions.Status.PROPOSED, decisions.Status.DECIDED, decisions.Status.SUPERSEDED):
        entries = decisions.by_status(status)
        if not entries:
            continue
        lines += [f"## {status.value.capitalize()} ({len(entries)})", "", "| ID | Title | Question / value | Sources | Code |", "|---|---|---|---|---|"]
        for d in entries:
            text = d.value if status is decisions.Status.DECIDED and d.value else d.question
            if d.note:
                text += f" *Note: {d.note}*"
            code = ", ".join(f"`{p}`" for p in use.get(d.id, [])) or "—"
            lines.append(f"| {d.id} | {d.title} | {text} | {', '.join(d.sources)} | {code} |")
        lines.append("")
    return "\n".join(lines)
