"""Generate `src/nagahana/governance/assumptions_build.py` from `docs/assumptions/*.md`.

The engineers of the L build wrote their assumptions (AS-100 …) as documents with full reasoning and
evidence. This script turns each section into a registry entry, so code can call `assume("AS-xxx")`
and the report can list who relies on what. The documents stay the single source of the text:
re-run this script after editing them.

    python tools/gen_assumptions.py

Parsing rules
-------------
- A section starts at a heading `## AS-NNN<sep> Title` or `### AS-NNN<sep> Title` (sep ∈ ":", "·", " ").
- `value`: the text after the "Assumed" label, else the first paragraph of the section.
- `stands_for`: decision, proposal and assumption IDs (D-xx, P-xx, AS-xx) named on the "Stands for"
  line, else ("detail",).
- `why`: a pointer to the section (file and heading), where the reasoning and evidence are written.
"""

from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "assumptions"
OUT = ROOT / "src" / "nagahana" / "governance" / "assumptions_build.py"

HEAD = re.compile(r"^#{2,3}\s+(AS-\d{3})\s*[:·]?\s*(.+?)\s*$")
IDS = re.compile(r"\b(?:D|P|AS)-\d+[a-c]?\b")


def _label(body: list[str], name: str) -> str:
    # Text of a "**Name:**" / "**Name.**" bullet, joined over its continuation lines.
    out: list[str] = []
    taking = False
    for line in body:
        stripped = line.strip()
        if re.match(rf"^-\s+\*\*{name}[:.]?\*\*[:.]?", stripped):
            taking = True
            out.append(re.sub(rf"^-\s+\*\*{name}[:.]?\*\*[:.]?\s*", "", stripped))
            continue
        if taking:
            if stripped.startswith("- ") or stripped.startswith("#") or not stripped:
                break
            out.append(stripped)
    return " ".join(out).strip()


def _first_paragraph(body: list[str]) -> str:
    para: list[str] = []
    for line in body:
        if not line.strip():
            if para:
                break
            continue
        para.append(line.strip().lstrip("- "))
    return " ".join(para).strip()


def _slug(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return s[:60] or "assumption"


def parse() -> list[tuple[str, str, str, tuple[str, ...], str, str, str]]:
    entries = []
    for doc in sorted(DOCS.glob("*.md")):
        lines = doc.read_text(encoding="utf-8").splitlines()
        heads = [(i, HEAD.match(line)) for i, line in enumerate(lines)]
        heads = [(i, m) for i, m in heads if m]
        for n, (i, m) in enumerate(heads):
            end = heads[n + 1][0] if n + 1 < len(heads) else len(lines)
            # Stop at the next heading of any level so trailing sections are not swallowed.
            for j in range(i + 1, end):
                if lines[j].startswith("#"):
                    end = j
                    break
            body = lines[i + 1 : end]
            aid, title = m.group(1), m.group(2).strip()
            value = _label(body, "Assumed") or _first_paragraph(body)
            stands = tuple(dict.fromkeys(IDS.findall(_label(body, "Stands for")))) or ("detail",)
            entries.append((aid, _slug(title), title, stands, value, f"docs/assumptions/{doc.name} § {aid}", doc.stem))
    ids = [e[0] for e in entries]
    dup = {i for i in ids if ids.count(i) > 1}
    if dup:
        raise SystemExit(f"duplicate assumption IDs: {sorted(dup)}")
    return entries


def main() -> None:
    entries = parse()
    out = [
        '"""Engineering assumptions AS-100 … of the L build. GENERATED by tools/gen_assumptions.py from',
        "docs/assumptions/*.md — do not edit by hand; edit the documents and re-run the script.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from nagahana.governance.assumption_types import Assumption",
        "",
        "BUILD_ENTRIES: tuple[Assumption, ...] = (",
    ]
    for aid, slug, title, stands, value, why, area in entries:
        out.append(f"    Assumption({aid!r}, {slug!r}, {title!r}, {stands!r},")
        out.append(f"               {value!r},")
        out.append(f"               {('Reasoning and evidence: ' + why)!r}, (), ({area!r},)),")
    out.append(")")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {len(entries)} entries to {OUT.relative_to(ROOT)}")
    write_table()


def _cell(text: str, limit: int = 220) -> str:
    # One table cell: single line, pipes escaped, long text cut at a word boundary.
    t = " ".join(text.split()).replace("|", "\\|")
    return t if len(t) <= limit else t[:limit].rsplit(" ", 1)[0] + " …"


def write_table() -> None:
    """Regenerate the table in docs/assumptions.md from the live registry (AS-01 … and AS-100 …)."""
    import importlib
    import sys

    sys.path.insert(0, str(ROOT / "src"))
    for mod in ("nagahana.governance.assumptions_build", "nagahana.governance.assumptions"):
        if mod in sys.modules:
            importlib.reload(sys.modules[mod])
    from nagahana.governance.assumptions import all_entries

    rows = ["| ID | Assumption | Stands for | What is assumed | Reasoning and evidence |", "|---|---|---|---|---|"]
    for a in all_entries():
        where = a.why if a.why.startswith("Reasoning and evidence:") else _cell(a.why, 200)
        ev = ("; ".join(a.evidence)) if a.evidence else ""
        rows.append(f"| {a.id} | {_cell(a.title, 80)} | {', '.join(a.stands_for)} | {_cell(a.value)} | "
                    f"{_cell(where + (' — ' + ev if ev else ''), 260)} |")
    doc = ROOT / "docs" / "assumptions.md"
    text = doc.read_text(encoding="utf-8")
    begin, end = "<!-- BEGIN GENERATED TABLE -->", "<!-- END GENERATED TABLE -->"
    i, j = text.index(begin) + len(begin), text.index(end)
    doc.write_text(text[:i] + "\n" + "\n".join(rows) + "\n" + text[j:], encoding="utf-8")
    print(f"wrote {len(rows) - 2} rows to docs/assumptions.md")


if __name__ == "__main__":
    main()
